/**
 * The example project: a generic machine, kept deliberately terse,
 * rebuilt from the demonstration's example against the current metamodel
 * and attribute definitions. It is held in the schema's own file shape
 * and loaded through the ordinary open path, gates and all, so it is
 * also a living fixture of the format: a schema change that breaks it
 * breaks a test before it breaks a user.
 *
 * The content is illustrative and holds no engineering judgement. No
 * text from any standard is reproduced: the requirements taken from a
 * standard carry a clause number and a topic, nothing more. The
 * specification that is not harmonised is a placeholder, named the way
 * the notified body is: nothing real is identified as carrying no
 * presumption of conformity.
 */

export const EXAMPLE_PROJECT = {
  format: 'openconformity-project',
  schemaVersion: 1,
  name: 'Example machine',
  counters: {
    LEG: 3, HST: 5, OSP: 2, CAS: 3, NTB: 2,
    ESR: 8, HSR: 9, OSR: 2, REQ: 6, VER: 5,
    HAZ: 7, SCN: 5, PRM: 7, SAF: 5,
    ELM: 9, ACT: 4, TSK: 5, PHS: 5,
    F: 17,
  },
  folders: [
    { id: 'F-1', name: 'Legislation and standards', parent: null, order: 0 },
    { id: 'F-2', name: 'European legislation', parent: 'F-1', order: 0 },
    { id: 'F-3', name: 'Conformity assessment', parent: 'F-1', order: 1 },
    { id: 'F-4', name: 'Harmonised standards', parent: 'F-1', order: 2 },
    { id: 'F-5', name: 'Other specifications', parent: 'F-1', order: 3 },
    { id: 'F-6', name: 'System and hazards', parent: null, order: 1 },
    { id: 'F-7', name: 'Elements', parent: 'F-6', order: 0 },
    { id: 'F-8', name: 'Actors', parent: 'F-6', order: 1 },
    { id: 'F-9', name: 'Phases', parent: 'F-6', order: 2 },
    { id: 'F-10', name: 'Risks and mitigations', parent: null, order: 2 },
    { id: 'F-11', name: 'Accident scenarios', parent: 'F-10', order: 0 },
    { id: 'F-12', name: 'Protective measures', parent: 'F-10', order: 1 },
    { id: 'F-13', name: 'Safety functions', parent: 'F-10', order: 2 },
    { id: 'F-14', name: 'Requirements definition', parent: null, order: 3 },
    { id: 'F-15', name: 'System requirements', parent: 'F-14', order: 0 },
    { id: 'F-16', name: 'System verifications', parent: 'F-14', order: 1 },
  ],
  entities: [
    { id: 'LEG-001', type: 'LEG', parent: 'F-2', order: 0, attributes: { title: 'Machinery Regulation (EU) 2023/1230', description: 'Applies to the machine as placed on the market.' } },
    { id: 'ESR-001', type: 'ESR', parent: 'LEG-001', order: 0, attributes: { title: '1.2.4.3 Emergency Stop', description: 'Machinery shall be fitted with an emergency stop device.' } },
    { id: 'ESR-002', type: 'ESR', parent: 'LEG-001', order: 1, attributes: { title: '1.3.7 Moving Parts', description: 'Moving parts shall prevent contact, or be guarded.' } },
    { id: 'ESR-003', type: 'ESR', parent: 'LEG-001', order: 2, attributes: { title: '1.4.2 Guards', description: 'Guards shall be robust, held in place and hard to defeat.' } },
    { id: 'ESR-004', type: 'ESR', parent: 'LEG-001', order: 3, attributes: { title: '1.5.1 Electricity', description: 'Electrically powered machinery shall prevent electrical hazards.' } },
    { id: 'ESR-005', type: 'ESR', parent: 'LEG-001', order: 4, attributes: { title: '1.6.3 Isolation of Energy Sources', description: 'Machinery shall provide a means to isolate its energy sources.' } },
    { id: 'LEG-002', type: 'LEG', parent: 'F-2', order: 1, attributes: { title: 'EMC Directive 2014/30/EU', description: 'Applies to the electrical equipment of the machine.' } },
    { id: 'ESR-006', type: 'ESR', parent: 'LEG-002', order: 0, attributes: { title: 'Annex I 1.1 Protection Requirements', description: 'Equipment shall not generate disturbance above the intended level.' } },
    { id: 'ESR-007', type: 'ESR', parent: 'LEG-002', order: 1, attributes: { title: 'Annex I 1.2 Immunity', description: 'Equipment shall work as intended in the presence of disturbance.' } },
    { id: 'CAS-001', type: 'CAS', parent: 'F-3', order: 0, attributes: { title: 'Internal Control', description: 'Assessed by the manufacturer, without a notified body.' } },
    { id: 'CAS-002', type: 'CAS', parent: 'F-3', order: 1, attributes: { title: 'EU Type-Examination', description: 'Assessed by a notified body for the safety component.' } },
    { id: 'NTB-001', type: 'NTB', parent: 'CAS-002', order: 0, attributes: { title: 'Notified Body', description: 'Placeholder. No real body is named in this example.' } },
    { id: 'HST-001', type: 'HST', parent: 'F-4', order: 0, attributes: { title: 'EN ISO 12100 Safety of machinery — General principles for design', description: 'Type A standard. The framework for the risk assessment.' } },
    { id: 'HSR-001', type: 'HSR', parent: 'HST-001', order: 0, attributes: { title: '5.4 Risk Estimation', description: 'How severity, exposure and avoidance combine into a risk.' } },
    { id: 'HSR-002', type: 'HSR', parent: 'HST-001', order: 1, attributes: { title: '6.2 Inherently Safe Design', description: 'Measures that remove a hazard by design rather than by guarding.' } },
    { id: 'HST-002', type: 'HST', parent: 'F-4', order: 1, attributes: { title: 'EN ISO 13849-1 Safety-related parts of control systems', description: 'Type B standard. Applied to the safety functions.' } },
    { id: 'HSR-003', type: 'HSR', parent: 'HST-002', order: 0, attributes: { title: '4.5 Required Performance Level', description: 'How the performance level required of a function is determined.' } },
    { id: 'HSR-004', type: 'HSR', parent: 'HST-002', order: 1, attributes: { title: '6.2 Category Requirements', description: 'What the designated architecture has to achieve.' } },
    { id: 'HST-003', type: 'HST', parent: 'F-4', order: 2, attributes: { title: 'EN ISO 14119 Interlocking devices associated with guards', description: 'Type B standard. Applied to the guard interlock.' } },
    { id: 'HSR-005', type: 'HSR', parent: 'HST-003', order: 0, attributes: { title: '5 Interlock Selection', description: 'How an interlocking device is chosen for a guard.' } },
    { id: 'HSR-006', type: 'HSR', parent: 'HST-003', order: 1, attributes: { title: '7 Prevention of Defeat', description: 'How defeat with a spare actuator is prevented.' } },
    { id: 'HST-004', type: 'HST', parent: 'F-4', order: 3, attributes: { title: 'EN 60204-1 Electrical equipment of machines', description: 'Type B standard. Applied to the electrical equipment.' } },
    { id: 'HSR-007', type: 'HSR', parent: 'HST-004', order: 0, attributes: { title: '9.2 Stop Categories', description: 'The stop categories, and when each one applies.' } },
    { id: 'HSR-008', type: 'HSR', parent: 'HST-004', order: 1, attributes: { title: '5.3 Supply Disconnecting Device', description: 'The device that isolates the electrical supply.' } },
    { id: 'OSP-001', type: 'OSP', parent: 'F-5', order: 0, attributes: { title: 'Other Specification', description: 'Placeholder. A specification applied to the machine that is not harmonised to the legislation, so it carries no presumption of conformity. Nothing real is named in this example.' } },
    { id: 'OSR-001', type: 'OSR', parent: 'OSP-001', order: 0, attributes: { title: 'Other Requirement', description: 'Placeholder. A requirement of the specification above. It supports an essential requirement rather than covering one, because the specification it comes from is not harmonised.' } },
    { id: 'ELM-001', type: 'ELM', parent: 'F-7', order: 0, attributes: { title: 'Machine', description: 'The machinery placed on the market.' } },
    { id: 'ELM-002', type: 'ELM', parent: 'ELM-001', order: 0, attributes: { title: 'Control System', description: 'Controls the machine and evaluates the safety inputs.' } },
    { id: 'ELM-003', type: 'ELM', parent: 'ELM-002', order: 0, attributes: { title: 'Safety Controller', description: 'Safety-related part of the control system.' } },
    { id: 'ELM-004', type: 'ELM', parent: 'ELM-002', order: 1, attributes: { title: 'Emergency Stop Device', description: 'Mushroom-head device at the operating position.' } },
    { id: 'HAZ-003', type: 'HAZ', parent: 'ELM-002', order: 2, attributes: { title: 'Unexpected Start-up', description: 'Mechanical hazard. The machine starts while someone is inside the guarding.' } },
    { id: 'ELM-005', type: 'ELM', parent: 'ELM-001', order: 1, attributes: { title: 'Drive Unit', description: 'Motor and gearbox driving the moving parts.' } },
    { id: 'HAZ-001', type: 'HAZ', parent: 'ELM-005', order: 0, attributes: { title: 'Moving Parts', description: 'Mechanical hazard. Rotating and translating parts in the drive area.' } },
    { id: 'HAZ-002', type: 'HAZ', parent: 'ELM-005', order: 1, attributes: { title: 'Stored Energy', description: 'Mechanical hazard. Energy held in the drive after the supply is removed.' } },
    { id: 'HAZ-006', type: 'HAZ', parent: 'ELM-005', order: 2, attributes: { title: 'Hot Surface', description: 'Thermal hazard. Surfaces of the drive that stay hot after a run.' } },
    { id: 'ELM-006', type: 'ELM', parent: 'ELM-001', order: 2, attributes: { title: 'Guarding', description: 'Fixed panels enclosing the drive area, with one access door.' } },
    { id: 'ELM-007', type: 'ELM', parent: 'ELM-006', order: 0, attributes: { title: 'Interlock Switch', description: 'Coded interlocking device on the guard door.' } },
    { id: 'ELM-008', type: 'ELM', parent: 'ELM-001', order: 3, attributes: { title: 'Electrical Cabinet', description: 'Houses the supply, the drives and the control gear.' } },
    { id: 'HAZ-004', type: 'HAZ', parent: 'ELM-008', order: 0, attributes: { title: 'Live Parts', description: 'Electrical hazard. Terminals that stay live when the main switch is off.' } },
    { id: 'HAZ-005', type: 'HAZ', parent: 'ELM-008', order: 1, attributes: { title: 'Short Circuit', description: 'Electrical hazard. A fault current in the electrical equipment.' } },
    { id: 'ACT-001', type: 'ACT', parent: 'F-8', order: 0, attributes: { title: 'Operator', description: 'Runs the machine and clears jams.' } },
    { id: 'ACT-002', type: 'ACT', parent: 'F-8', order: 1, attributes: { title: 'Maintenance Technician', description: 'Services the machine with the guards open.' } },
    { id: 'ACT-003', type: 'ACT', parent: 'F-8', order: 2, attributes: { title: 'Cleaner', description: 'Cleans the machine after a production run.' } },
    { id: 'PHS-001', type: 'PHS', parent: 'F-9', order: 0, attributes: { title: 'Installation', description: 'The machine is put in place and connected.' } },
    { id: 'PHS-002', type: 'PHS', parent: 'F-9', order: 1, attributes: { title: 'Operation', description: 'The machine runs the production programme.' } },
    { id: 'TSK-001', type: 'TSK', parent: 'PHS-002', order: 0, attributes: { title: 'Load Material', description: 'Material is fed into the machine.' } },
    { id: 'TSK-002', type: 'TSK', parent: 'PHS-002', order: 1, attributes: { title: 'Clear Jam', description: 'A blockage in the product path is freed by hand.' } },
    { id: 'PHS-003', type: 'PHS', parent: 'F-9', order: 2, attributes: { title: 'Maintenance', description: 'Planned service and repair.' } },
    { id: 'TSK-003', type: 'TSK', parent: 'PHS-003', order: 0, attributes: { title: 'Replace Part', description: 'A worn part is exchanged inside the guarding.' } },
    { id: 'TSK-004', type: 'TSK', parent: 'PHS-003', order: 1, attributes: { title: 'Clean Machine', description: 'Residue is removed from the product path.' } },
    { id: 'PHS-004', type: 'PHS', parent: 'F-9', order: 3, attributes: { title: 'Decommissioning', description: 'The machine is taken out of service.' } },
    { id: 'SCN-001', type: 'SCN', parent: 'F-11', order: 0, attributes: { title: 'Contact with Moving Parts', description: 'Hazard zone: Drive Unit.\nHazardous situation: Operator reaches into the drive area to clear a jam.\nHazardous event: Drive starts while the hand is in the hazard zone.\nPotential consequence: Crushing of the hand.' } },
    { id: 'SCN-002', type: 'SCN', parent: 'F-11', order: 1, attributes: { title: 'Electric Shock', description: 'Hazard zone: Electrical Cabinet.\nHazardous situation: Technician works in the cabinet with the supply connected.\nHazardous event: Contact with a live part.\nPotential consequence: Electric shock.' } },
    { id: 'SCN-003', type: 'SCN', parent: 'F-11', order: 2, attributes: { title: 'Start-up During Maintenance', description: 'Hazard zone: Guarded Area.\nHazardous situation: Technician inside the guarding with the machine not isolated.\nHazardous event: Machine restarts.\nPotential consequence: Crushing.' } },
    { id: 'SCN-004', type: 'SCN', parent: 'F-11', order: 3, attributes: { title: 'Burn on Hot Surface', description: 'Hazard zone: Drive Unit.\nHazardous situation: Cleaner works close to the drive after a production run.\nHazardous event: Contact with a hot surface.\nPotential consequence: Burn to the hand.' } },
    { id: 'PRM-001', type: 'PRM', parent: 'F-12', order: 0, attributes: { title: 'Fixed Guard', description: 'Panels that enclose the drive area.' } },
    { id: 'PRM-002', type: 'PRM', parent: 'F-12', order: 1, attributes: { title: 'Interlocked Guard', description: 'Access door with a coded interlock and guard locking.' } },
    { id: 'PRM-003', type: 'PRM', parent: 'F-12', order: 2, attributes: { title: 'Emergency Stop', description: 'Device that stops the machine on demand.' } },
    { id: 'PRM-004', type: 'PRM', parent: 'F-12', order: 3, attributes: { title: 'Energy Isolation', description: 'Lockable device that removes the electrical supply.' } },
    { id: 'PRM-005', type: 'PRM', parent: 'F-12', order: 4, attributes: { title: 'Warning Label', description: 'Marking at the hot surface of the drive.' } },
    { id: 'PRM-006', type: 'PRM', parent: 'F-12', order: 5, attributes: { title: 'Instructions for Use', description: 'Procedure for clearing a jam with the machine stopped.' } },
    { id: 'SAF-001', type: 'SAF', parent: 'F-13', order: 0, attributes: { title: 'Emergency Stop', description: 'Stops all drives when an emergency stop device is operated.\nRequired performance level: PL c, category 1.\nTriggering event: Emergency stop device operated.\nSafety-related reaction: Power removed from all drives.\nDefined safe state: Drives at standstill, restart inhibited.' } },
    { id: 'SAF-002', type: 'SAF', parent: 'F-13', order: 1, attributes: { title: 'Door Interlock', description: 'Stops the drives when the guard door is opened and prevents restart.\nRequired performance level: PL d, category 3.\nTriggering event: Guard door opened.\nSafety-related reaction: Power removed from the drives.\nDefined safe state: Drives at standstill, restart inhibited.' } },
    { id: 'SAF-003', type: 'SAF', parent: 'SAF-002', order: 0, attributes: { title: 'Position Detection', description: 'Detects the guard door position on two channels.\nRequired performance level: PL d, category 3.\nTriggering event: Guard door leaves the closed position.\nSafety-related reaction: Both channels signal open.\nDefined safe state: Guard reported open.' } },
    { id: 'SAF-004', type: 'SAF', parent: 'SAF-002', order: 1, attributes: { title: 'Safe Torque Off', description: 'Removes torque from the drives on two channels.\nRequired performance level: PL d, category 3.\nTriggering event: Stop demanded by the safety controller.\nSafety-related reaction: Drive enable removed on both channels.\nDefined safe state: No torque at the drives.' } },
    { id: 'REQ-001', type: 'REQ', parent: 'F-15', order: 0, attributes: { title: 'Access Protection', description: 'The machine shall prevent access to the drive area while the drives can move.\nRationale: Access to the drive area is the common cause of the recorded scenarios.\nType: Function/Performance.' } },
    { id: 'REQ-002', type: 'REQ', parent: 'REQ-001', order: 0, attributes: { title: 'Guard Fastening', description: 'The machine shall retain fixed guards with fasteners that stay attached to the guard.\nRationale: Loose fasteners are why a guard is left off after maintenance.\nType: Form.' } },
    { id: 'REQ-003', type: 'REQ', parent: 'REQ-001', order: 1, attributes: { title: 'Guard Interlocking', description: 'While the drives can move, the machine shall keep the guard door locked closed.\nRationale: The drives overrun after a stop command.\nType: Function/Performance.' } },
    { id: 'REQ-004', type: 'REQ', parent: 'F-15', order: 1, attributes: { title: 'Emergency Stop Devices', description: 'The machine shall provide an emergency stop device at each operating position.\nRationale: Required at every position occupied while the machine can move.\nType: Compliance.' } },
    { id: 'REQ-005', type: 'REQ', parent: 'F-15', order: 2, attributes: { title: 'Supply Isolation', description: 'The machine shall provide a lockable device that isolates the electrical supply.\nRationale: Maintenance is carried out inside the guarding.\nType: Fit/Operational.' } },
    { id: 'VER-001', type: 'VER', parent: 'F-16', order: 0, attributes: { title: 'Emergency Stop Test', description: 'Operate each emergency stop device during a cycle.\nMethod: Test.\nAcceptance criteria: All drives stop and the machine does not restart on release.' } },
    { id: 'VER-002', type: 'VER', parent: 'F-16', order: 1, attributes: { title: 'Interlock Test', description: 'Open the guard door during a cycle.\nMethod: Test.\nAcceptance criteria: The door stays locked until standstill is reached.' } },
    { id: 'VER-003', type: 'VER', parent: 'F-16', order: 2, attributes: { title: 'Guard Inspection', description: 'Remove each fixed guard panel.\nMethod: Inspection.\nAcceptance criteria: No fastener separates from the guard without a tool.' } },
    { id: 'VER-004', type: 'VER', parent: 'F-16', order: 3, attributes: { title: 'Circuit Analysis', description: 'Review the safety circuit against the claimed architecture and reliability data.\nMethod: Analysis.\nAcceptance criteria: The achieved performance level is not lower than the required one.' } },
  ],
  relationships: [
    { type: 'elm-decomposes-into-elm', source: 'ELM-001', target: 'ELM-002' },
    { type: 'elm-decomposes-into-elm', source: 'ELM-001', target: 'ELM-005' },
    { type: 'elm-decomposes-into-elm', source: 'ELM-001', target: 'ELM-006' },
    { type: 'elm-decomposes-into-elm', source: 'ELM-001', target: 'ELM-008' },
    { type: 'elm-decomposes-into-elm', source: 'ELM-002', target: 'ELM-003' },
    { type: 'elm-decomposes-into-elm', source: 'ELM-002', target: 'ELM-004' },
    { type: 'elm-decomposes-into-elm', source: 'ELM-006', target: 'ELM-007' },
    { type: 'act-interacts-with-elm', source: 'ACT-001', target: 'ELM-001' },
    { type: 'act-interacts-with-elm', source: 'ACT-002', target: 'ELM-001' },
    { type: 'act-interacts-with-elm', source: 'ACT-003', target: 'ELM-001' },
    { type: 'elm-undergoes-phs', source: 'ELM-001', target: 'PHS-001' },
    { type: 'elm-undergoes-phs', source: 'ELM-001', target: 'PHS-002' },
    { type: 'elm-undergoes-phs', source: 'ELM-001', target: 'PHS-003' },
    { type: 'elm-undergoes-phs', source: 'ELM-001', target: 'PHS-004' },
    { type: 'act-performs-tsk', source: 'ACT-001', target: 'TSK-001' },
    { type: 'act-performs-tsk', source: 'ACT-001', target: 'TSK-002' },
    { type: 'act-performs-tsk', source: 'ACT-002', target: 'TSK-003' },
    { type: 'act-performs-tsk', source: 'ACT-003', target: 'TSK-004' },
    { type: 'tsk-occurs-during-phs', source: 'TSK-001', target: 'PHS-002' },
    { type: 'tsk-occurs-during-phs', source: 'TSK-002', target: 'PHS-002' },
    { type: 'tsk-occurs-during-phs', source: 'TSK-003', target: 'PHS-003' },
    { type: 'tsk-occurs-during-phs', source: 'TSK-004', target: 'PHS-003' },
    { type: 'elm-subject-to-leg', source: 'ELM-001', target: 'LEG-001' },
    { type: 'elm-subject-to-leg', source: 'ELM-001', target: 'LEG-002' },
    { type: 'elm-applies-hst', source: 'ELM-001', target: 'HST-001' },
    { type: 'elm-applies-hst', source: 'ELM-002', target: 'HST-002' },
    { type: 'elm-applies-hst', source: 'ELM-007', target: 'HST-003' },
    { type: 'elm-applies-hst', source: 'ELM-008', target: 'HST-004' },
    { type: 'elm-applies-osp', source: 'ELM-002', target: 'OSP-001' },
    { type: 'leg-contains-esr', source: 'LEG-001', target: 'ESR-001' },
    { type: 'leg-contains-esr', source: 'LEG-001', target: 'ESR-002' },
    { type: 'leg-contains-esr', source: 'LEG-001', target: 'ESR-003' },
    { type: 'leg-contains-esr', source: 'LEG-001', target: 'ESR-004' },
    { type: 'leg-contains-esr', source: 'LEG-001', target: 'ESR-005' },
    { type: 'leg-contains-esr', source: 'LEG-002', target: 'ESR-006' },
    { type: 'leg-contains-esr', source: 'LEG-002', target: 'ESR-007' },
    { type: 'cas-conducted-under-leg', source: 'CAS-001', target: 'LEG-001' },
    { type: 'cas-conducted-under-leg', source: 'CAS-002', target: 'LEG-001' },
    { type: 'ntb-performs-cas', source: 'NTB-001', target: 'CAS-002' },
    { type: 'hst-harmonised-under-leg', source: 'HST-001', target: 'LEG-001' },
    { type: 'hst-harmonised-under-leg', source: 'HST-002', target: 'LEG-001' },
    { type: 'hst-harmonised-under-leg', source: 'HST-003', target: 'LEG-001' },
    { type: 'hst-harmonised-under-leg', source: 'HST-004', target: 'LEG-001' },
    { type: 'hst-contains-hsr', source: 'HST-001', target: 'HSR-001' },
    { type: 'hst-contains-hsr', source: 'HST-001', target: 'HSR-002' },
    { type: 'hst-contains-hsr', source: 'HST-002', target: 'HSR-003' },
    { type: 'hst-contains-hsr', source: 'HST-002', target: 'HSR-004' },
    { type: 'hst-contains-hsr', source: 'HST-003', target: 'HSR-005' },
    { type: 'hst-contains-hsr', source: 'HST-003', target: 'HSR-006' },
    { type: 'hst-contains-hsr', source: 'HST-004', target: 'HSR-007' },
    { type: 'hst-contains-hsr', source: 'HST-004', target: 'HSR-008' },
    { type: 'osp-contains-osr', source: 'OSP-001', target: 'OSR-001' },
    { type: 'elm-exhibits-haz', source: 'ELM-005', target: 'HAZ-001' },
    { type: 'elm-exhibits-haz', source: 'ELM-005', target: 'HAZ-002' },
    { type: 'elm-exhibits-haz', source: 'ELM-005', target: 'HAZ-006' },
    { type: 'elm-exhibits-haz', source: 'ELM-002', target: 'HAZ-003' },
    { type: 'elm-exhibits-haz', source: 'ELM-008', target: 'HAZ-004' },
    { type: 'elm-exhibits-haz', source: 'ELM-008', target: 'HAZ-005' },
    { type: 'haz-contributes-to-scn', source: 'HAZ-001', target: 'SCN-001' },
    { type: 'haz-contributes-to-scn', source: 'HAZ-003', target: 'SCN-003' },
    { type: 'haz-contributes-to-scn', source: 'HAZ-004', target: 'SCN-002' },
    { type: 'haz-contributes-to-scn', source: 'HAZ-006', target: 'SCN-004' },
    { type: 'esr-triggered-by-haz', source: 'ESR-002', target: 'HAZ-001' },
    { type: 'esr-triggered-by-haz', source: 'ESR-005', target: 'HAZ-002' },
    { type: 'esr-triggered-by-haz', source: 'ESR-001', target: 'HAZ-003' },
    { type: 'esr-triggered-by-haz', source: 'ESR-004', target: 'HAZ-004' },
    { type: 'esr-triggered-by-haz', source: 'ESR-004', target: 'HAZ-005' },
    { type: 'esr-triggered-by-haz', source: 'ESR-003', target: 'HAZ-006' },
    { type: 'tsk-gives-rise-to-scn', source: 'TSK-002', target: 'SCN-001' },
    { type: 'tsk-gives-rise-to-scn', source: 'TSK-003', target: 'SCN-002' },
    { type: 'tsk-gives-rise-to-scn', source: 'TSK-003', target: 'SCN-003' },
    { type: 'tsk-gives-rise-to-scn', source: 'TSK-004', target: 'SCN-004' },
    { type: 'act-exposed-in-scn', source: 'ACT-001', target: 'SCN-001' },
    { type: 'act-exposed-in-scn', source: 'ACT-002', target: 'SCN-002' },
    { type: 'act-exposed-in-scn', source: 'ACT-002', target: 'SCN-003' },
    { type: 'act-exposed-in-scn', source: 'ACT-003', target: 'SCN-004' },
    { type: 'prm-eliminates-haz', source: 'PRM-001', target: 'HAZ-001' },
    { type: 'prm-eliminates-haz', source: 'PRM-002', target: 'HAZ-001' },
    { type: 'prm-eliminates-haz', source: 'PRM-003', target: 'HAZ-003' },
    { type: 'prm-eliminates-haz', source: 'PRM-004', target: 'HAZ-002' },
    { type: 'prm-eliminates-haz', source: 'PRM-004', target: 'HAZ-004' },
    { type: 'prm-eliminates-haz', source: 'PRM-005', target: 'HAZ-006' },
    { type: 'prm-reduces-risk-of-scn', source: 'PRM-002', target: 'SCN-001' },
    { type: 'prm-reduces-risk-of-scn', source: 'PRM-004', target: 'SCN-002' },
    { type: 'prm-reduces-risk-of-scn', source: 'PRM-004', target: 'SCN-003' },
    { type: 'prm-reduces-risk-of-scn', source: 'PRM-006', target: 'SCN-004' },
    { type: 'prm-implements-hsr', source: 'PRM-002', target: 'HSR-005' },
    { type: 'prm-implements-hsr', source: 'PRM-002', target: 'HSR-006' },
    { type: 'prm-implements-hsr', source: 'PRM-003', target: 'HSR-007' },
    { type: 'prm-implements-osr', source: 'PRM-003', target: 'OSR-001' },
    { type: 'saf-decomposes-into-saf', source: 'SAF-002', target: 'SAF-003' },
    { type: 'saf-decomposes-into-saf', source: 'SAF-002', target: 'SAF-004' },
    { type: 'saf-realises-prm', source: 'SAF-001', target: 'PRM-003' },
    { type: 'saf-realises-prm', source: 'SAF-002', target: 'PRM-002' },
    { type: 'prm-allocated-to-elm', source: 'PRM-001', target: 'ELM-006' },
    { type: 'prm-allocated-to-elm', source: 'PRM-002', target: 'ELM-007' },
    { type: 'prm-allocated-to-elm', source: 'PRM-003', target: 'ELM-004' },
    { type: 'prm-allocated-to-elm', source: 'PRM-004', target: 'ELM-008' },
    { type: 'saf-allocated-to-elm', source: 'SAF-001', target: 'ELM-003' },
    { type: 'saf-allocated-to-elm', source: 'SAF-002', target: 'ELM-003' },
    { type: 'saf-allocated-to-elm', source: 'SAF-003', target: 'ELM-007' },
    { type: 'saf-allocated-to-elm', source: 'SAF-004', target: 'ELM-005' },
    { type: 'hsr-covers-esr', source: 'HSR-002', target: 'ESR-002' },
    { type: 'hsr-covers-esr', source: 'HSR-003', target: 'ESR-002' },
    { type: 'hsr-covers-esr', source: 'HSR-005', target: 'ESR-003' },
    { type: 'hsr-covers-esr', source: 'HSR-006', target: 'ESR-003' },
    { type: 'hsr-covers-esr', source: 'HSR-007', target: 'ESR-001' },
    { type: 'hsr-covers-esr', source: 'HSR-008', target: 'ESR-005' },
    { type: 'osr-supports-esr', source: 'OSR-001', target: 'ESR-001' },
    { type: 'elm-satisfies-esr', source: 'ELM-005', target: 'ESR-002' },
    { type: 'elm-satisfies-esr', source: 'ELM-006', target: 'ESR-003' },
    { type: 'elm-satisfies-esr', source: 'ELM-008', target: 'ESR-004' },
    { type: 'elm-satisfies-esr', source: 'ELM-002', target: 'ESR-006' },
    { type: 'elm-satisfies-hsr', source: 'ELM-007', target: 'HSR-005' },
    { type: 'elm-satisfies-hsr', source: 'ELM-003', target: 'HSR-003' },
    { type: 'elm-satisfies-osr', source: 'ELM-003', target: 'OSR-001' },
    { type: 'req-decomposes-into-req', source: 'REQ-001', target: 'REQ-002' },
    { type: 'req-decomposes-into-req', source: 'REQ-001', target: 'REQ-003' },
    { type: 'req-derives-from-hsr', source: 'REQ-003', target: 'HSR-005' },
    { type: 'req-derives-from-hsr', source: 'REQ-003', target: 'HSR-006' },
    { type: 'req-derives-from-hsr', source: 'REQ-004', target: 'HSR-007' },
    { type: 'req-derives-from-osr', source: 'REQ-004', target: 'OSR-001' },
    { type: 'req-expresses-prm', source: 'REQ-002', target: 'PRM-001' },
    { type: 'req-expresses-prm', source: 'REQ-004', target: 'PRM-003' },
    { type: 'req-expresses-prm', source: 'REQ-005', target: 'PRM-004' },
    { type: 'req-expresses-saf', source: 'REQ-003', target: 'SAF-002' },
    { type: 'req-expresses-saf', source: 'REQ-004', target: 'SAF-001' },
    { type: 'elm-satisfies-req', source: 'ELM-005', target: 'REQ-001' },
    { type: 'elm-satisfies-req', source: 'ELM-006', target: 'REQ-002' },
    { type: 'elm-satisfies-req', source: 'ELM-007', target: 'REQ-003' },
    { type: 'elm-satisfies-req', source: 'ELM-004', target: 'REQ-004' },
    { type: 'elm-satisfies-req', source: 'ELM-008', target: 'REQ-005' },
    { type: 'ver-verifies-req', source: 'VER-001', target: 'REQ-004' },
    { type: 'ver-verifies-req', source: 'VER-002', target: 'REQ-003' },
    { type: 'ver-verifies-req', source: 'VER-003', target: 'REQ-002' },
  ],
};
